networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

services:
  postgres:
    image: "postgres:14"
    container_name: "video_encoder_postgres"
    environment:
      POSTGRES_USER: "bhumit070"
      POSTGRES_PASSWORD: "bhumit070"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    ports:
      - "5001:5432"
    restart: unless-stopped

  backend:
    build:
      dockerfile: ./docker/Api.Dockerfile
      context: ../
    container_name: "video_encoder_backend"
    volumes:
      - ../:/app
    ports:
      - 8080:8080

  job:
    build:
      dockerfile: ./docker/BackgroundJob.Dockerfile
      context: ../
    container_name: "video_encoder_job"
    volumes:
      - ../:/app
    ports:
      - 8081:8081

  localstack:
    image: localstack/localstack-pro
    container_name: "video_encoder_localstack"
    entrypoint: ["/scripts/localstack.sh"]
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    volumes:
      - ./data/localstack/bootstrap:/opt/bootstrap/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/localstack/state:/var/lib/localstack/state
      - ./data/localstack/volume/:/var/lib/localstack
      - ./scripts/localstack.sh:/scripts/localstack.sh
    env_file:
      - path: "./env/localstack.env"
        required: false
    networks:
      custom_network:
        ipv4_address: 192.168.1.100
